---
apiVersion: v1
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
      scrape_timeout: 10s
      evaluation_interval: 15s
    alerting:
      alertmanagers:
        - static_configs:
            - targets: []
          scheme: http
          timeout: 10s
          api_version: v1
    scrape_configs:
      - job_name: grafana
        scheme: http
        static_configs:
          - targets:
              - grafana:3000
      - job_name: prometheus
        scheme: http
        static_configs:
          - targets:
              - localhost:9090
      - job_name: traefik
        scheme: http
        static_configs:
          - targets:
              - traefik:9000
kind: ConfigMap
metadata:
  name: prometheus
