networks:
  locally:

services:
  angular:
    build:
      context: ../angular
      dockerfile: ../.docker/angular.dockerfile
    networks:
      - locally
    ports:
      - 8000:80

version: '3.8'
