jobs:
  build_angular:
    defaults:
      run:
        working-directory: angular
    name: build_angular
    runs-on: ubuntu-20.04
    steps:
      - name: actions_checkout
        uses: actions/checkout@v2.3.2
      - name: npm_install
        run: npm clean-install
      - name: npm_lint
        run: npm run lint
      - name: npm_build
        run: npm run build

name: build

on:
  pull_request:
    branches:
      - main
